In [11]:
import numpy as np
a = np.array([3,4,6,4,3,5])

In [12]:
V = np.array([[[6,2,2],[6,9,4],[1,8,5],[11,8,3]], [[1,2,3],[6,5,4],[7,8,5], [11,45,3]]])
W = np.array([[66,4,6],[9,8,11],[67,12,34]])
u_w = np.array([[1,2,3], [5,9,7]])

In [13]:
# otg: vtori chlen array([ 2839,  6142,  7813, 15261])
VWu_w = np.einsum("sij,jk,sk->si",V,W,u_w)
VWu_w

array([[ 1054,  1846,  1521,  2055],
       [ 2839,  6142,  7813, 15261]])

In [14]:
# vtori chlen 
# # array([[ 285,   56,  130],
#        [ 709,  112,  227],
#        [ 869,  152,  300],
#        [1332,  440,  663]])
delta = np.zeros(shape=V.shape[1])
delta[0] = 1
sig_matrix = VWu_w - delta
sig_matrix[1]

array([ 2838.,  6142.,  7813., 15261.])

In [15]:
a = np.array([ 2839,  6142,  7813, 15261]) - delta
b = np.array([[ 285,   56,  130],
       [ 709,  112,  227],
      [ 869,  152,  300],
       [1332,  440,  663]])
np.einsum('i,ij->j',a,b)

array([32280657.,  8749248., 14225117.])

In [16]:
VW = np.einsum("sij,jk->sik",V, W) # Sx(n+1)xM
du_w = np.einsum("si,sij->sj", sig_matrix, VW)
du_w

array([[ 4724692.,   823824.,  1560568.],
       [32280657.,  8749248., 14225117.]])

In [17]:
du_w1 = np.einsum('i,ij->j', sig_matrix[1], VW[1])
du_w1

array([32280657.,  8749248., 14225117.])

In [18]:
V[0][0,:]

array([6, 2, 2])

In [21]:
VW

array([[[ 548,   64,  126],
        [ 745,  144,  271],
        [ 473,  128,  264],
        [ 999,  144,  256]],

       [[ 285,   56,  130],
        [ 709,  112,  227],
        [ 869,  152,  300],
        [1332,  440,  663]]])

In [23]:
2*VW

array([[[1096,  128,  252],
        [1490,  288,  542],
        [ 946,  256,  528],
        [1998,  288,  512]],

       [[ 570,  112,  260],
        [1418,  224,  454],
        [1738,  304,  600],
        [2664,  880, 1326]]])

In [ ]:
for i in range(few_matrices.shape[0]):
    print(np.matmul(few_matrices[i], other))

[[164 206]
 [328 412]
 [492 618]]
[[1476 1854]
 [1230 1545]
 [ 984 1236]]
[[1148 1442]
 [1312 1648]
 [ 820 1030]]
[[ 7216  9064]
 [29520 37080]
 [ 1968  2472]]


In [ ]:
np.matmul(V,np.array([3,4,5]))


array([ 26,  58,  78, 228])

In [ ]:
b = np.array([-1,1,1])
c = np.array([4,5,6,7])

V+b

array([[ 0,  3,  4],
       [ 5,  6,  5],
       [ 6,  9,  6],
       [10, 46,  4]])

In [ ]:
V

array([[ 1,  2,  3],
       [ 6,  5,  4],
       [ 7,  8,  5],
       [11, 45,  3]])

In [ ]:
np.einsum("ij,j->ij",V,b)

array([[ -1,   2,   3],
       [ -6,   5,   4],
       [ -7,   8,   5],
       [-11,  45,   3]])