In [2]:
import torch

t = torch.randn(32, 1, 5, 5)

/home/hsani/envs/irdl_env/lib/python3.8/site-packages/tqdm/auto.py:22: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


In [3]:
t.shape

torch.Size([32, 1, 5, 5])

In [4]:
torch.tensor([3]).shape

torch.Size([1])

In [5]:
input = torch.randn(3, 5, requires_grad=True)
target = torch.randint(5, (3,), dtype=torch.int64)
input,target

(tensor([[ 0.6084,  0.3697, -0.2986, -1.0460, -1.9165],
         [ 0.3544, -1.2377,  0.5545, -0.0732,  0.7147],
         [-1.0473,  0.6306, -1.3820, -0.4766,  0.3478]], requires_grad=True),
 tensor([2, 0, 1]))

In [6]:
target/2

tensor([1.0000, 0.0000, 0.5000])

In [9]:
a = [1,2,3,4]
a[-3:]

[2, 3, 4]